### ISSUE TITLE
can't use django-admin dumpdata because of config issues

### ISSUE THREAD

**Issue by EMCain** [EMCain/pandaid-api#7]
steps to duplicate: run `django-admin dumpdata pandaid_base` in the Docker shell. It'll get an error that mentions configuration. I'm planning into looking into this more later but maybe someone else could help if they have time. 

Goal is to be able to use the dumpdata and loaddata features to generate and use fixtures.

**Comment by geophpherie** [comment]
I think you may be able to get around this by using `python manage.py dumpdata` instead. I get the same error with `django-admin`but using `manage.py` at least spits out a bunch of text and doesn't error. Can look into it more later.

**Comment by bhgrant8** [comment]
appears that we may have an acceptable workaround, @jbeyer16 could you confirm?

**Comment by geophpherie** [comment]
I think so. From the docs [here](https://docs.djangoproject.com/en/3.0/ref/django-admin/) it appears that `manage.py` does the exact same thing as `django-admin` but it specifically sets the `DJANGO_SETTINGS_MODULE` to point to the settings. So that explains the issue. Running `python manage.py pandaid_base` currently returns no data, but it does execute. Running `python manage.py` will return what appears to be our database model. So I think we can close this issue at least.
